const CHAIN_LOGO_SLUG: Record<string, string> = {
  // EVM
  Ethereum: "ethereum",
  Base: "base",
  Arbitrum: "arbitrum",
  Optimism: "optimism",
  Polygon: "polygon",
  BSC: "smartchain",
  Avalanche: "avalanchec",
  Fantom: "fantom",
  zkSync: "zksync",
  Linea: "linea",
  Scroll: "scroll",
  Mantle: "mantle",
  "Ethereum Classic": "classic",
  HyperEVM: "ethereum",
  HyperCore: "ethereum",
  // L1
  Bitcoin: "bitcoin",
  "Lightning Network": "lightning",
  Solana: "solana",
  Tron: "tron",
  TON: "ton",
  Polkadot: "polkadot",
  NEAR: "near",
  Dogecoin: "doge",
  Litecoin: "litecoin",
  "Bitcoin Cash": "bitcoincash",
  ZCash: "zcash",
  Monero: "monero",
  "XRP Ledger": "xrp",
  Stellar: "stellar",
  Bittensor: "bittensor",
  Cardano: "cardano",
  Filecoin: "filecoin",
  Hedera: "hedera",
  Kaspa: "kaspa",
  Algorand: "algorand",
  MultiversX: "elrond",
  Starknet: "starknet",
  // Cosmos
  "Cosmos Hub": "cosmos",
  Osmosis: "osmosis",
  Celestia: "celestia",
  dYdX: "dydx",
  Injective: "injective",
  Sei: "sei",
  Stride: "stride",
  Stargaze: "stargaze",
  Akash: "akash",
  Axelar: "axelar",
  Kava: "kava",
  Juno: "juno",
  Evmos: "evmos",
  Secret: "secret",
  Band: "band",
  Persistence: "persistence",
  Regen: "regen",
  Sommelier: "sommelier",
  Chihuahua: "cosmos",
  Archway: "archway",
  Noble: "noble",
  Neutron: "neutron",
  Coreum: "coreum",
  KYVE: "kyve",
  Agoric: "agoric",
  Terra: "terra",
  IRISnet: "iris",
  "Cronos POS": "cronos",
  Dymension: "dymension",
  MANTRA: "cosmos",
  Babylon: "cosmos",
  Nolus: "cosmos",
  Pryzm: "cosmos",
  // Move
  Sui: "sui",
  Aptos: "aptos",
};

export function getChainLogoUrl(chainName: string): string | undefined {
  const slug = CHAIN_LOGO_SLUG[chainName];
  if (!slug) return undefined;
  return `https://multiscan.dev/logos/${slug}.png`;
}
