const CHAIN_LOGO_SLUG: Record<string, string> = {
  // EVM
  Ethereum: "ethereum",
  Base: "base",
  Arbitrum: "arbitrum",
  Optimism: "optimism",
  Polygon: "polygon",
  BSC: "smartchain",
  Avalanche: "avalanchec",
  Fantom: "fantom",
  zkSync: "zksync",
  Linea: "linea",
  Scroll: "scroll",
  Mantle: "mantle",
  "Ethereum Classic": "classic",
  HyperEVM: "hyperliquid",
  HyperCore: "hyperliquid",
  // L1
  Bitcoin: "bitcoin",
  "Lightning Network": "lightning",
  Solana: "solana",
  Tron: "tron",
  TON: "ton",
  Polkadot: "polkadot",
  NEAR: "near",
  Dogecoin: "doge",
  Litecoin: "litecoin",
  "Bitcoin Cash": "bitcoincash",
  ZCash: "zcash",
  Monero: "monero",
  "XRP Ledger": "xrp",
  Stellar: "stellar",
  Bittensor: "bittensor",
  Cardano: "cardano",
  Filecoin: "filecoin",
  Hedera: "hedera",
  Kaspa: "kaspa",
  Algorand: "algorand",
  MultiversX: "elrond",
  Starknet: "starknet",
  // Cosmos
  "Cosmos Hub": "cosmos",
  Osmosis: "osmosis",
  Celestia: "celestia",
  dYdX: "dydx",
  Injective: "injective",
  Sei: "sei",
  Stride: "stride",
  Stargaze: "stargaze",
  Akash: "akash",
  Axelar: "axelar",
  Kava: "kava",
  Juno: "juno",
  Evmos: "evmos",
  Secret: "secret",
  Band: "band",
  Persistence: "persistence",
  Regen: "regen",
  Sommelier: "sommelier",
  Chihuahua: "cosmos",
  Archway: "archway",
  Noble: "noble",
  Neutron: "neutron",
  Coreum: "coreum",
  KYVE: "kyve",
  Agoric: "agoric",
  Terra: "terra",
  IRISnet: "iris",
  "Cronos POS": "cronos",
  Dymension: "dymension",
  MANTRA: "cosmos",
  Babylon: "cosmos",
  Nolus: "cosmos",
  Pryzm: "cosmos",
  // Move
  Sui: "sui",
  Aptos: "aptos",
  // Testnets (reuse mainnet logos)
  "Ethereum Sepolia": "ethereum",
  "Ethereum Holesky": "ethereum",
  "Base Sepolia": "base",
  "Arbitrum Sepolia": "arbitrum",
  "Optimism Sepolia": "optimism",
  "Polygon Amoy": "polygon",
  "BSC Testnet": "smartchain",
  "Avalanche Fuji": "avalanchec",
  "Fantom Testnet": "fantom",
  "zkSync Sepolia": "zksync",
  "Linea Sepolia": "linea",
  "Scroll Sepolia": "scroll",
  "Mantle Sepolia": "mantle",
  "Bitcoin Testnet": "bitcoin",
  "Solana Testnet": "solana",
  "Solana Devnet": "solana",
  "Cardano Preprod": "cardano",
  "Sui Testnet": "sui",
  "Aptos Testnet": "aptos",
  "NEAR Testnet": "near",
  "Tron Shasta": "tron",
  "Tron Nile": "tron",
  "TON Testnet": "ton",
  "Starknet Sepolia": "starknet",
  "XRP Testnet": "xrp",
  "Stellar Testnet": "stellar",
  "Hedera Testnet": "hedera",
  "Algorand Testnet": "algorand",
  "MultiversX Devnet": "elrond",
  "Polkadot Westend": "polkadot",
  "Filecoin Calibration": "filecoin",
  "Litecoin Testnet": "litecoin",
  "Dogecoin Testnet": "doge",
  "Bitcoin Cash Testnet": "bitcoincash",
  "ZCash Testnet": "zcash",
  "Kaspa Testnet": "kaspa",
  Dash: "dash",
  Urbit: "urbit",
  "Dash Testnet": "dash",
  "Lightning Testnet": "lightning",
  "Ethereum Classic Mordor": "classic",
  "HyperEVM Testnet": "hyperliquid",
  "HyperCore Testnet": "hyperliquid",
  "Osmosis Testnet": "osmosis",
  "Celestia Testnet": "celestia",
  "dYdX Testnet": "dydx",
  "Injective Testnet": "injective",
  "Axelar Testnet": "axelar",
  "Kava Testnet": "kava",
  "Persistence Testnet": "persistence",
  "Archway Testnet": "archway",
  "Noble Testnet": "noble",
  "Neutron Testnet": "neutron",
  "Coreum Testnet": "coreum",
  "MANTRA Testnet": "cosmos",
  "Babylon Testnet": "cosmos",
};

export function getChainLogoUrl(chainName: string): string | undefined {
  const slug = CHAIN_LOGO_SLUG[chainName];
  if (!slug) return undefined;
  return `https://multiscan.dev/logos/${slug}.png`;
}
