const L = (file: string) => `/logos/${file}.png`;

export const CHAIN_LOGO: Record<string, string> = {
  // EVM
  Ethereum: L("ethereum"),
  Base: L("base"),
  Arbitrum: L("arbitrum"),
  Optimism: L("optimism"),
  Polygon: L("polygon"),
  BSC: L("smartchain"),
  Avalanche: L("avalanchec"),
  Fantom: L("fantom"),
  zkSync: L("zksync"),
  Linea: L("linea"),
  Scroll: L("scroll"),
  Mantle: L("mantle"),
  "Ethereum Classic": L("classic"),
  HyperEVM: L("ethereum"),
  HyperCore: L("ethereum"),
  // L1
  Bitcoin: L("bitcoin"),
  "Lightning Network": L("lightning"),
  Solana: L("solana"),
  Tron: L("tron"),
  TON: L("ton"),
  Polkadot: L("polkadot"),
  NEAR: L("near"),
  Dogecoin: L("doge"),
  Litecoin: L("litecoin"),
  "Bitcoin Cash": L("bitcoincash"),
  ZCash: L("zcash"),
  Monero: L("monero"),
  "XRP Ledger": L("xrp"),
  Stellar: L("stellar"),
  Bittensor: L("bittensor"),
  Cardano: L("cardano"),
  Filecoin: L("filecoin"),
  Hedera: L("hedera"),
  Kaspa: L("kaspa"),
  Algorand: L("algorand"),
  MultiversX: L("elrond"),
  Starknet: L("starknet"),
  // Cosmos
  "Cosmos Hub": L("cosmos"),
  Osmosis: L("osmosis"),
  Celestia: L("celestia"),
  dYdX: L("dydx"),
  Injective: L("injective"),
  Sei: L("sei"),
  Stride: L("stride"),
  Stargaze: L("stargaze"),
  Akash: L("akash"),
  Axelar: L("axelar"),
  Kava: L("kava"),
  Juno: L("juno"),
  Evmos: L("evmos"),
  Secret: L("secret"),
  Band: L("band"),
  Persistence: L("persistence"),
  Regen: L("regen"),
  Sommelier: L("sommelier"),
  Chihuahua: L("cosmos"),
  Archway: L("archway"),
  Noble: L("noble"),
  Neutron: L("neutron"),
  Coreum: L("coreum"),
  KYVE: L("kyve"),
  Agoric: L("agoric"),
  Terra: L("terra"),
  IRISnet: L("iris"),
  "Cronos POS": L("cronos"),
  Dymension: L("dymension"),
  MANTRA: L("cosmos"),
  Babylon: L("cosmos"),
  Nolus: L("cosmos"),
  Pryzm: L("cosmos"),
  // Move
  Sui: L("sui"),
  Aptos: L("aptos"),
};
