const L = (file: string) => `/logos/${file}.png`;

export const CHAIN_LOGO: Record<string, string> = {
  // EVM
  Ethereum: L("ethereum"),
  Base: L("base"),
  Arbitrum: L("arbitrum"),
  Optimism: L("optimism"),
  Polygon: L("polygon"),
  BSC: L("smartchain"),
  Avalanche: L("avalanchec"),
  Fantom: L("fantom"),
  zkSync: L("zksync"),
  Linea: L("linea"),
  Scroll: L("scroll"),
  Mantle: L("mantle"),
  "Ethereum Classic": L("classic"),
  HyperEVM: L("hyperliquid"),
  HyperCore: L("hyperliquid"),
  // L1
  Bitcoin: L("bitcoin"),
  "Lightning Network": L("lightning"),
  Solana: L("solana"),
  Tron: L("tron"),
  TON: L("ton"),
  Polkadot: L("polkadot"),
  NEAR: L("near"),
  Dogecoin: L("doge"),
  Litecoin: L("litecoin"),
  "Bitcoin Cash": L("bitcoincash"),
  ZCash: L("zcash"),
  Monero: L("monero"),
  "XRP Ledger": L("xrp"),
  Stellar: L("stellar"),
  Bittensor: L("bittensor"),
  Cardano: L("cardano"),
  Filecoin: L("filecoin"),
  Hedera: L("hedera"),
  Kaspa: L("kaspa"),
  Algorand: L("algorand"),
  MultiversX: L("elrond"),
  Starknet: L("starknet"),
  // Cosmos
  "Cosmos Hub": L("cosmos"),
  Osmosis: L("osmosis"),
  Celestia: L("celestia"),
  dYdX: L("dydx"),
  Injective: L("injective"),
  Sei: L("sei"),
  Stride: L("stride"),
  Stargaze: L("stargaze"),
  Akash: L("akash"),
  Axelar: L("axelar"),
  Kava: L("kava"),
  Juno: L("juno"),
  Evmos: L("evmos"),
  Secret: L("secret"),
  Band: L("band"),
  Persistence: L("persistence"),
  Regen: L("regen"),
  Sommelier: L("sommelier"),
  Chihuahua: L("cosmos"),
  Archway: L("archway"),
  Noble: L("noble"),
  Neutron: L("neutron"),
  Coreum: L("coreum"),
  KYVE: L("kyve"),
  Agoric: L("agoric"),
  Terra: L("terra"),
  IRISnet: L("iris"),
  "Cronos POS": L("cronos"),
  Dymension: L("dymension"),
  MANTRA: L("cosmos"),
  Babylon: L("cosmos"),
  Nolus: L("cosmos"),
  Pryzm: L("cosmos"),
  // Move
  Sui: L("sui"),
  Aptos: L("aptos"),
  // Testnets (reuse mainnet logos)
  "Ethereum Sepolia": L("ethereum"),
  "Ethereum Holesky": L("ethereum"),
  "Base Sepolia": L("base"),
  "Arbitrum Sepolia": L("arbitrum"),
  "Optimism Sepolia": L("optimism"),
  "Polygon Amoy": L("polygon"),
  "BSC Testnet": L("smartchain"),
  "Avalanche Fuji": L("avalanchec"),
  "Fantom Testnet": L("fantom"),
  "zkSync Sepolia": L("zksync"),
  "Linea Sepolia": L("linea"),
  "Scroll Sepolia": L("scroll"),
  "Mantle Sepolia": L("mantle"),
  "Bitcoin Testnet": L("bitcoin"),
  "Solana Testnet": L("solana"),
  "Solana Devnet": L("solana"),
  "Cardano Preprod": L("cardano"),
  "Sui Testnet": L("sui"),
  "Aptos Testnet": L("aptos"),
  "NEAR Testnet": L("near"),
  "Tron Shasta": L("tron"),
  "Tron Nile": L("tron"),
  "TON Testnet": L("ton"),
  "Starknet Sepolia": L("starknet"),
  "XRP Testnet": L("xrp"),
  "Stellar Testnet": L("stellar"),
  "Hedera Testnet": L("hedera"),
  "Algorand Testnet": L("algorand"),
  "MultiversX Devnet": L("elrond"),
  "Polkadot Westend": L("polkadot"),
  "Filecoin Calibration": L("filecoin"),
  "Litecoin Testnet": L("litecoin"),
  "Dogecoin Testnet": L("doge"),
  "Bitcoin Cash Testnet": L("bitcoincash"),
  "ZCash Testnet": L("zcash"),
  "Kaspa Testnet": L("kaspa"),
  Tezos: L("tezos"),
  Aleo: L("aleo"),
  Nano: L("nano"),
  Chia: L("chia"),
  Dash: L("dash"),
  Urbit: L("urbit"),
  "Dash Testnet": L("dash"),
  "Lightning Testnet": L("lightning"),
  "Ethereum Classic Mordor": L("classic"),
  "HyperEVM Testnet": L("hyperliquid"),
  "HyperCore Testnet": L("hyperliquid"),
  "Osmosis Testnet": L("osmosis"),
  "Celestia Testnet": L("celestia"),
  "dYdX Testnet": L("dydx"),
  "Injective Testnet": L("injective"),
  "Axelar Testnet": L("axelar"),
  "Kava Testnet": L("kava"),
  "Persistence Testnet": L("persistence"),
  "Archway Testnet": L("archway"),
  "Noble Testnet": L("noble"),
  "Neutron Testnet": L("neutron"),
  "Coreum Testnet": L("coreum"),
  "MANTRA Testnet": L("cosmos"),
  "Babylon Testnet": L("cosmos"),
  THORChain: L("thorchain"),
  Berachain: L("berachain"),
  "Berachain Testnet": L("berachain"),
  Ronin: L("ronin"),
  "Ronin Saigon": L("ronin"),
  Flare: L("flare"),
  "Flare Coston2": L("flare"),
  "Oasis Sapphire": L("oasis"),
  "Oasis Sapphire Testnet": L("oasis"),
  Core: L("core"),
  "Core Testnet": L("core"),
  Monad: L("monad"),
  "Monad Testnet": L("monad"),
  MegaETH: L("megaeth"),
  Plasma: L("plasma"),
};
